# version: 1.0.0
# Nordic-darker color palette
#2e3440	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	docker & shell
#81a1c1>

# Background  -   Blend color
format = """
[░▒▓](#2e3440)\
$username\
[](bg:#3b4252 fg:#353B49)\
$directory\
[](bg:#434c5e fg:#3F4758)\
$git_branch\
$git_status\
[](bg:#4c566a fg:#485164)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$lua\
[](bg:#5e81ac fg:#556C8B)\
$docker_context\
$shlvl\
[ ](fg:#81a1c1)\
\n
$cmd_duration\
$character\
"""
add_newline = true

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#d08770"
format = '[󰯉  $user ]($style)'
disabled = false

[shlvl]
disabled = false
format = '[ $symbol ]($style)'
symbol = '  '
style = "bg:#5e81ac"

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dots" = " "

[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[  $all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#5e81ac"
format = '[  $time ]($style)'

[character]
success_symbol = '[  ](white)'
error_symbol = '[  ](#bf616a)'

[cmd_duration]
min_time = 500
format = ' [$duration](white)'
